# Generated by Django 3.1.3 on 2020-11-22 18:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_auto_20201123_0020'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='productinfo',
            options={'managed': True},
        ),
    ]
