# Generated by Django 3.1.3 on 2020-11-22 18:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_auto_20201123_0022'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='productinfo',
            options={},
        ),
        migrations.AlterModelTable(
            name='productinfo',
            table=None,
        ),
    ]
