# Generated by Django 3.1.3 on 2020-12-05 09:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0011_productinfo_company'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='productinfo',
            table='ProdctInfo',
        ),
    ]
