# Generated by Django 3.1.3 on 2020-12-05 09:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0012_auto_20201205_1448'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='productinfo',
            table='Prodctinfo',
        ),
    ]
